---

- name: Add Midokura repos
  template:
    src: midokura.list.j2
    dest: /etc/apt/sources.list.d/midokura.list

- name: Add Midokura repos key
  apt_key:
    url: "{{ midonet_base_url }}/midorepo.key"
  retries: 3
