---

- name: Add repository file for apt
  template:
    dest: '/etc/apt/sources.list.d/midonet.list'
    group: 'root'
    mode: 0644
    owner: 'root'
    src: 'midonet.list.j2'

- name: Add Midokura repos key
  apt_key:
    url: '{{ midonet_repo_repository_gpgkey_url }}'

- name: Add OpenJDK 8 ppa repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  when: ansible_distribution_release == 'trusty'

- name: apt-get update
  apt:
    update_cache: yes
